[character]
success_symbol    = '[](bold green)'

[directory]
truncation_length = 8
truncation_symbol = '…/'
home_symbol       = '~  '

[username]
style_user = 'yellow bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '@[$hostname](bold cyan) '
trim_at = '.companyname.com'
disabled = false

#programming langs
[python]
symbol = ' '
[c]
symbol = ' '

#[git]
[git_branch]
symbol = ' '
truncation_length = 4
truncation_symbol = ''
[git_commit]
commit_hash_length = 4
tag_symbol = '󰜘 '
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ PICKING](bold red)'
[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
[git_status]
style = 'yellow bold'
conflicted = '  '
ahead = ' ${count}'
diverged = '󰦻 ${ahead_count}⇣${behind_count}'
behind = ' ${count}'
up_to_date = '  ✓ '
untracked = '󱚆 '
stashed = '  '
modified = ' 󰷥 '
staged = '[++\($count\)](green)'
renamed = ' 󱈤 '
deleted = ' 󰩹 '
